// <auto-generated />
namespace _01_SportsBetting.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class BettingInformationChanged : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BettingInformationChanged));
        
        string IMigrationMetadata.Id
        {
            get { return "202111031834448_Betting Information Changed"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
