// <auto-generated />
namespace _01_SportsBetting.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Something : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Something));
        
        string IMigrationMetadata.Id
        {
            get { return "202110282018439_Something"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
